language: c
compiler:
 - gcc
before_script:
 - git clone git://github.com/jedisct1/libsodium.git
 - cd libsodium
 - ./autogen.sh
 - ./configure --disable-dependency-tracking
 - sudo make install
 - sudo ldconfig
 - cd ..
 script:
 - make
 - dd if=/dev/urandom of=/tmp/password count=42
 - dd if=/dev/urandom of=/tmp/orig count=10000
 - (echo example@example.com ; cat /tmp/password /tmp/password) | ./example/example -e /tmp/orig > /tmp/enc
 - (echo example@example.com ; cat /tmp/password) | ./example/example -d /tmp/enc > /tmp/dec
 - cmp /tmp/dec /tmp/orig
