language: c
compiler:
 - gcc
before_script:
 - git clone git://github.com/jedisct1/libsodium.git
 - cd libsodium
 - ./autogen.sh
 - ./configure --disable-dependency-tracking
 - sudo make install
 - sudo ldconfig
 - cd ..
 script:
 - make
 - ./example/example -e /etc/group > /tmp/a && ./example/example -d /tmp/a > /tmp/b && cmp /tmp/b /etc/group
